[2024-01-22T20:24:50.155+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_sample_dag.test scheduled__2022-05-28T00:00:00+00:00 [queued]>
[2024-01-22T20:24:50.176+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_sample_dag.test scheduled__2022-05-28T00:00:00+00:00 [queued]>
[2024-01-22T20:24:50.178+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-01-22T20:24:50.195+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): test> on 2022-05-28 00:00:00+00:00
[2024-01-22T20:24:50.210+0000] {standard_task_runner.py:60} INFO - Started process 219 to run task
[2024-01-22T20:24:50.230+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'first_sample_dag', 'test', 'scheduled__2022-05-28T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/sample_dag.py', '--cfg-path', '/tmp/tmp2nqvd6uf']
[2024-01-22T20:24:50.235+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask test
[2024-01-22T20:24:51.087+0000] {task_command.py:423} INFO - Running <TaskInstance: first_sample_dag.test scheduled__2022-05-28T00:00:00+00:00 [running]> on host 8b57cbef3a15
[2024-01-22T20:24:51.251+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_sample_dag' AIRFLOW_CTX_TASK_ID='test' AIRFLOW_CTX_EXECUTION_DATE='2022-05-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-05-28T00:00:00+00:00'
[2024-01-22T20:24:51.258+0000] {logging_mixin.py:188} INFO - asdf
[2024-01-22T20:24:51.259+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-22T20:24:51.280+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=first_sample_dag, task_id=test, execution_date=20220528T000000, start_date=20240122T202450, end_date=20240122T202451
[2024-01-22T20:24:51.344+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-22T20:24:51.416+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-22T20:51:41.167+0000] {taskinstance.py:1946} INFO - Dependencies not met for <TaskInstance: first_sample_dag.test scheduled__2022-05-28T00:00:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-01-22T20:51:41.169+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
